// GENERATED by scripts/build-validator-bundle.ts — do not edit by hand.
// Auto-discovers engine/art/<name>/index.ts directories.
import type { ArtProvider } from "./_primitives.ts";
import * as p0 from "./blocks/index.ts";
import * as p1 from "./skulls/index.ts";
import * as p2 from "./topo/index.ts";

export const ART: Record<string, ArtProvider["renderArt"]> = {
  [p0.id]: p0.renderArt,
  [p1.id]: p1.renderArt,
  [p2.id]: p2.renderArt,
};
