#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env --allow-net --allow-run
// Bundle engine/browser.ts + all transitive deps (including JSON-LD contexts
// via "json" loader) into a single ESM file the browser validator imports
// directly: ./validator-bundle.js. Run after any engine source change that
// touches browser-facing code.

import * as esbuild from "npm:esbuild@^0.25";
import { denoPlugins } from "jsr:@luca/esbuild-deno-loader@^0.11";
import { dirname, fromFileUrl, join, resolve, toFileUrl } from "jsr:@std/path@^1";

const scriptDir = dirname(fromFileUrl(import.meta.url));
const repoRoot = resolve(scriptDir, "..");
const artDir = resolve(repoRoot, "engine", "art");
const entryPoint = toFileUrl(resolve(repoRoot, "engine", "browser.ts")).href;
const outfile = resolve(repoRoot, "validator-bundle.js");
const configPath = resolve(repoRoot, "deno.json");

/** Discover art providers in engine/art/<name>/index.ts and write a registry
 *  file that imports each and exports a map keyed by its `id`. */
async function generateArtRegistry(): Promise<string[]> {
  const providers: Array<{ dir: string }> = [];
  for await (const entry of Deno.readDir(artDir)) {
    if (!entry.isDirectory || entry.name.startsWith("_")) continue;
    try {
      await Deno.stat(join(artDir, entry.name, "index.ts"));
      providers.push({ dir: entry.name });
    } catch (_e) {
      // No index.ts — skip.
    }
  }
  providers.sort((a, b) => a.dir.localeCompare(b.dir));

  const imports = providers
    .map((p, i) => `import * as p${i} from "./${p.dir}/index.ts";`)
    .join("\n");
  const entries = providers
    .map((_p, i) => `  [p${i}.id]: p${i}.renderArt,`)
    .join("\n");
  const body = `// GENERATED by scripts/build-validator-bundle.ts — do not edit by hand.
// Auto-discovers engine/art/<name>/index.ts directories.
import type { ArtProvider } from "./_primitives.ts";
${imports}

export const ART: Record<string, ArtProvider["renderArt"]> = {
${entries}
};
`;
  await Deno.writeTextFile(join(artDir, "_index.generated.ts"), body);
  return providers.map((p) => p.dir);
}

const providerDirs = await generateArtRegistry();
console.log(`Art registry: ${providerDirs.join(", ")}`);

const result = await esbuild.build({
  plugins: [...denoPlugins({ configPath })],
  entryPoints: [entryPoint],
  outfile,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  metafile: true,
});

esbuild.stop();

const sizeKb = (await Deno.stat(outfile)).size / 1024;
console.log(`Wrote ${outfile} (${sizeKb.toFixed(1)} KB)`);

if (result.warnings.length > 0) {
  console.warn(`${result.warnings.length} warning(s):`);
  for (const w of result.warnings) console.warn(`  ${w.text}`);
}
